version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app-image
    container_name: app-container
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8080:8080"

  json-server:
    container_name: json-server-container
    image: json-server-image
    build:
      context: .
      dockerfile: data/Dockerfile
    ports:
      - "3000:3000"
